/*

This file is generated by gen-constants.py. 2022-01-26 09:36:14.251550

Edit at your own risk!!!!

*/


/* /Users/jenkins/workspace/tailf/confd_dir/include/confd_ha.h */

/* Generated by clang -E -DCONFD_C_PRODUCT_CONFD -dD - command */

/* enum confd_ha_status_state { */
     ADD_CONST(CONFD_HA_STATE_NONE, "STATE_NONE");
     ADD_CONST(CONFD_HA_STATE_SLAVE, "STATE_SLAVE");
     ADD_CONST(CONFD_HA_STATE_MASTER, "STATE_MASTER");
     ADD_CONST(CONFD_HA_STATE_SLAVE_RELAY, "STATE_SLAVE_RELAY");
/* }; */
