#!/bin/sh

usage()
{
    cat <<EOF
Usage: ncs-java-start [-d|--debug]
EOF
}

DBGOPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=9000,server=y,suspend=n"

bindir=`dirname $0`
case $bindir in
    /*) ncs_dir=`dirname $bindir`;;
    *)  ncs_dir=`(cd $bindir/..; pwd)`;;
esac
# %LOCALSTART%
ncs_dir="${ncs_dir}/ncs_dir"
# %LOCALEND%

opts="-classpath ."
for i in `find ${NCS_DIR}/java/jar/*.jar`; do \
        opts="${opts}:$i"
done

while [ $# -gt 0 ]; do
    arg="$1"
    shift
    case "$arg" in
        -d | --debug)
            opts="${opts} ${DBGOPTS}"
            break;;
	-h | --help)
	    usage
	    exit;;
	*)
	    error "${arg}: Unknown option";;
    esac
done

## The memory size for the Java engine may need to be adjusted
## increase jave memory on macs
case `uname` in
    Darwin)
        mem=-Xmx512M
        ;;
    *)
        mem=
esac

exec java ${mem} ${opts} -Dport=5757 com.tailf.ncs.NcsJVMLauncher

