.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "API" "" "February 2016" "" ""
.
.SH "NAME"
\fBAPI\fR \- &product; specific
.
.SH "METHOD get_service_points"
Extracts paths to all &product; services
.
.SS "RESULT"
.
.nf

{"service_points": <array of key\-value objects>}
.
.fi
.
.SH "METHOD get_template_variables"
Extracts all variables from a &product; service/device template
.
.SS "PARAMS"
.
.nf

{"th": <number>,
 "name": <string>}
.
.fi
.
.P
The \fBname\fR param is the name of the template to extract variables from\.
.
.SS "RESULT"
.
.nf

{"template_variables": <array of string>}
.
.fi

