all:
	mkdir nso-lab-rundir
	ncs-setup --dest ./nso-lab-rundir
	cp init/Makefile.in nso-lab-rundir/Makefile
	cp init/ncs_init.xml.in nso-lab-rundir/ncs-cdb/ncs_init.xml
	cp -r init/router.in nso-lab-rundir/packages/router

clean:
	-rm -rf nso-lab-rundir

stop:
	-ncs-netsim --dir nso-lab-rundir/netsim -a stop
	-ncs --stop

showcase:
	./showcase.sh

showcase-rc:
	python3 ./showcase_rc.py
