'\" t
.\"     Title: ncs-installer
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/26/2022
.\"    Manual: NCS Manual
.\"    Source: Cisco Systems, Inc.
.\"  Language: English
.\"
.TH "NCS\-INSTALLER" "1" "01/26/2022" "Cisco Systems, Inc." "NCS Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncs-installer \- NCS installation script
.SH "SYNOPSIS"
.HP \w'\fBncs\-VSN\&.OS\&.ARCH\&.installer\&.bin\fR\ 'u
\fBncs\-VSN\&.OS\&.ARCH\&.installer\&.bin\fR [\-\-local\-install] \fILocalInstallDir\fR
.HP \w'\fBncs\-VSN\&.OS\&.ARCH\&.installer\&.bin\fR\ 'u
\fBncs\-VSN\&.OS\&.ARCH\&.installer\&.bin\fR \-\-system\-install [\-\-install\-dir\ \fIInstallDir\fR] [\-\-config\-dir\ \fIConfigDir\fR] [\-\-run\-dir\ \fIRunDir\fR] [\-\-log\-dir\ \fILogDir\fR] [\-\-run\-as\-user\ \fIUser\fR] [\-\-keep\-ncs\-setup] [\-\-non\-interactive]
.SH "DESCRIPTION"
.PP
The NCS installation script can be invoked to do either a simple "local installation", which is convenient for test and development purposes, or a "system installation", suitable for deployment\&.
.SH "LOCAL INSTALLATION"
.PP
\fB[ \-\-local\-install ] \fR\fB\fILocalInstallDir\fR\fR
.RS 4
When the NCS installation script is invoked with this option, or is given only the
\fILocalInstallDir\fR
argument, NCS will be installed in the
\fILocalInstallDir\fR
directory only\&.
.RE
.SH "SYSTEM INSTALLATION"
.PP
\fB\-\-system\-install\fR
.RS 4
When the NCS installation script is invoked with this option, it will do a system installation that uses several different directories, in accordance with Unix/Linux application installation standards\&. The first time a system installation is done, the following actions are taken:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The directories described below are created and populated\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
An init script for start of NCS at system boot is installed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
User profile scripts that set up
\fI$PATH\fR
and other environment variables appropriately for NCS users are installed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
A symbolic link that makes the installed version the currently active one is created (see the
\fB\-\-install\-dir\fR
option)\&.
.RE
.RE
.PP
\fB[ \-\-install\-dir \fR\fB\fIInstallDir\fR\fR\fB ]\fR
.RS 4
This is the directory where static files, primarily the code and libraries for the NCS daemon, are installed\&. The actual directory used for a given invocation of the installation script is
\fIInstallDir\fR/ncs\-VSN, allowing for coexistence of multiple installed versions\&. The currently active version is identified by a symbolic link
\fIInstallDir\fR/current
pointing to one of the
ncs\-VSN
directories\&. If the
\fB\-\-install\-dir\fR
option is omitted,
/opt/ncs
will be used for
\fIInstallDir\fR\&.
.RE
.PP
\fB[ \-\-config\-dir \fR\fB\fIConfigDir\fR\fR\fB ]\fR
.RS 4
This directory is used for config files, e\&.g\&.
ncs\&.conf\&. If the
\fB\-\-config\-dir\fR
option is omitted,
/etc/ncs
will be used for
\fIConfigDir\fR\&.
.RE
.PP
\fB[ \-\-run\-dir \fR\fB\fIRunDir\fR\fR\fB ]\fR
.RS 4
This directory is used for run\-time state files, such as the CDB data base and currently used packages\&. If the
\fB\-\-run\-dir\fR
option is omitted,
/var/opt/ncs
will be used for
\fIRunDir\fR\&.
.RE
.PP
\fB[ \-\-log\-dir \fR\fB\fILogDir\fR\fR\fB ]\fR
.RS 4
This directory is used for the different log files written by NCS\&. If the
\fB\-\-log\-dir\fR
option is omitted,
/var/log/ncs
will be used for
\fILogDir\fR\&.
.RE
.PP
\fB[ \-\-run\-as\-user \fR\fB\fIUser\fR\fR\fB ]\fR
.RS 4
By default, the system installation will run NCS as the
root
user\&. If a different user is given via this option, NCS will instead be run as that user\&. The user will be created if it does not already exist\&. This mode is only supported on Linux systems that have the
\fBsetcap\fR
command, since it is needed to give NCS components the required capabilities for some aspects of the NCS functionality\&.
.sp
When the option is used, the following executable files (assuming that the default
/opt/ncs
is used for
\fB\-\-install\-dir\fR) will be installed with elevated privileges:
.PP
/opt/ncs/current/lib/ncs/lib/core/pam/priv/epam
.RS 4
Setuid to root\&. This is typically needed for PAM authentication to work with a local password file\&. If PAM authentication is not used, or if the local PAM configuration does not require root privileges, the setuid\-root privilege can be removed by using
\fBchmod u\-s\fR\&.
.RE
.PP
/opt/ncs/current/lib/ncs/erts/bin/ncs /opt/ncs/current/lib/ncs/erts/bin/ncs\&.smp
.RS 4
Capability
cap_net_bind_service\&. One of these files (normally
ncs\&.smp) will be used as the NCS daemon\&. The files have execute access restricted to the user given via
\fB\-\-run\-as\-user\fR\&. The capability is needed to allow the daemon to bind to ports below 1024 for northbound access, e\&.g\&. port 443 for HTTPS or port 830 for NETCONF over SSH\&. If this functionality is not needed, the capability can be removed by using
\fBsetcap \-r\fR\&.
.RE
.PP
/opt/ncs/current/lib/ncs/bin/ip
.RS 4
Capability
cap_net_admin\&. This is a copy of the OS
\fBip(8)\fR
command, with execute access restricted to the user given via
\fB\-\-run\-as\-user\fR\&. The program is not used by the core NCS daemon, but provided for packages that need to configure IP addresses on interfaces (such as the
tailf\-hcc
package)\&. If no such packages are used, the file can be removed\&.
.RE
.PP
/opt/ncs/current/lib/ncs/bin/arping
.RS 4
Capability
cap_net_raw\&. This is a copy of the OS
\fBarping(8)\fR
command, with execute access restricted to the user given via
\fB\-\-run\-as\-user\fR\&. The program is not used by the core NCS daemon, but provided for packages that need to send gratuitous ARP requests (such as the
tailf\-hcc
package)\&. If no such packages are used, the file can be removed\&.
.RE
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
When the
\fB\-\-run\-as\-user\fR
option is used, all OS commands executed by NCS will also run as the given user, rather than as the user specified in e\&.g\&.
\m[blue]\fBclispec(5)\fR\m[]
definitions for custom CLI commands\&.
.sp .5v
.RE
.RE
.PP
\fB[ \-\-keep\-ncs\-setup ]\fR
.RS 4
The
\fBncs\-setup\fR
command is not usable in a "system installation", and is therefore by default excluded from such an installation to avoid confusion\&. This option instructs the installation script to include
\fBncs\-setup\fR
in the installation despite this\&.
.RE
.PP
\fB[ \-\-non\-interactive ]\fR
.RS 4
If this option is given, the installation script will proceed with potentially disruptive changes (e\&.g\&. modifying or removing existing files) without asking for confirmation\&.
.RE
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2021, 2022 Cisco Systems, Inc. All rights reserved.
.br
