'\" t
.\"     Title: ncs-project-export
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/26/2022
.\"    Manual: NCS Manual
.\"    Source: Cisco Systems, Inc.
.\"  Language: English
.\"
.TH "NCS\-PROJECT\-EXPORT" "1" "01/26/2022" "Cisco Systems, Inc." "NCS Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncs-project-export \- Command to create a bundle from a NCS project
.SH "SYNOPSIS"
.HP \w'\fBncs\-project\ export\ \fR\ 'u
\fBncs\-project export \fR [OPTIONS] project\-name
.SH "DESCRIPTION"
.PP
Collects relevant packages and files from an existing NCS project and saves them in a tar file \- a
\fIbundle\fR\&. This exported bundle can then be distributed to be unpacked, either with the
\fIncs\-project create\fR
command, or simply unpacked using the standard
\fItar\fR
command\&.
.PP
The bundle is declared in the
project\-meta\-data\&.xml
file in the
\fIbundle\fR
section\&. The packages included in the bundle are leafrefs to the packages defined at the root of the model\&. We can also define a specific tag, commit or branch, even a different location for the packages, different from the one used while developing\&. For example we might develop against an experimental branch of a repository, but bundle with a specific release of that same repository\&. Tags or commit SHA hashes are recommended since branch HEAD pointers usually are a moving target\&. Should a branch name be used, a warning is issued\&.
.PP
A list of extra files to be included can be specified\&.
.PP
Url references will not be built, i\&.e they will be added to the bundle as is\&.
.PP
The list of packages to be included in the bundle can be picked from git repositories or locally in the same way as when updating an NCS Project\&.
.PP
Note that the generated
project\-meta\-data\&.xml
file, included in the bundle, will specify all the packages as
\fIlocal\fR
to avoid any dangling pointers to non\-accessible git repositories\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Print debugging information when creating the bundle\&.
.RE
.PP
\fB\-\-prefix=<prefix>\fR
.RS 4
Add a prefix to the bundle file name\&. Cannot be used together with the name option\&.
.RE
.PP
\fB\-\-pkg\-prefix=<prefix>\fR
.RS 4
Use a specific prefix for the compressed packages used in the bundle instead of the default "ncs\-$lt;vsn>" where the <vsn> is the NCS version that ncs\-project is shipped with\&.
.RE
.PP
\fB\-\-name=<name>\fR
.RS 4
Skip any configured name and use
\fIname\fR
as the bundle file name\&.
.RE
.PP
\fB\-\-skip\-build\fR
.RS 4
When the packages have been retrieved from their different locations, this option will skip trying to build the packages\&. No (re\-)build will occur of the packages\&. This can be used to export a bundle for a different NCS version\&.
.RE
.PP
\fB\-\-skip\-pkg\-update\fR
.RS 4
This option will not try to use the package versions defined in the "bundle" part of the project\-meta\-data, but instead use whatever versions are installed in the "packages" directory\&. This can be used to export modified packages\&. Use with care\&.
.RE
.PP
\fB\-\-snapshot\fR
.RS 4
Add a timestamp to the bundle file name\&.
.RE
.SH "EXAMPLES"
.PP
Generate a bundle, this command is run in a directory containing a NSO project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  $ ncs\-project export
  Creating bundle \&.\&.\&.
  Creating bundle \&.\&.\&. ok
      
.fi
.if n \{\
.RE
.\}
.PP
We can also export a bundle with a specific name, below we will create a bundle called
test\&.tar\&.gz\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  $ ncs\-project export \-\-name=test
  Creating bundle \&.\&.\&.
  Creating bundle \&.\&.\&. ok
      
.fi
.if n \{\
.RE
.\}
.PP
Example of how to specify some extra files to be included into the bundle, in the
project\-meta\-data\&.xml
file\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  <bundle>
    <name>test_bundle</name>
    <includes>
      <file>
        <path>README</path>
      </file>
      <file>
        <path>ncs\&.conf</path>
      </file>
    </includes>
    \&.\&.\&.
  </bundle>
      
.fi
.if n \{\
.RE
.\}
.PP
Example of how to specify packages to be included in the bundle, in the
project\-meta\-data\&.xml
file\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  <bundle>
    \&.\&.\&.
    <package>
      <name>resource\-manager</name>
      <git>
        <repo>ssh://git@stash\&.tail\-f\&.com/pkg/resource\-manager\&.git</repo>
        <tag>1\&.2</tag>
      </git>
    </package>
    <!\-\- Use the repos specified in \*(Aq\&.\&./\&.\&./packages\-store\*(Aq \-\->
    <package>
      <name>id\-allocator</name>
      <git>
        <tag>1\&.0</tag>
      </git>
    </package>
    <!\-\- A local package \-\->
    <!\-\- (the version vill be picked from the package\-meta\-data\&.xml) \-\->
    <package>
      <name>my\-local</name>
      <local/>
    </package>
  </bundle>
      
.fi
.if n \{\
.RE
.\}
.PP
Example of how to extract only the packages using
\fItar\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  tar xzf my_bundle\-1\&.0\&.tar\&.gz my_bundle\-1\&.0/packages
      
.fi
.if n \{\
.RE
.\}
.PP
The command uses a temporary directory called
\fI\&.bundle\fR, the directory contains copies of the included packages, files and project\-meta\-data\&.xml\&. This temporary directory is removed by the export command\&. Should it remain for some reason it can safely be removed\&.
.PP
The tar\-ball can be extracted using
\fItar\fR
and the packages can be installed like any other packages\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2021, 2022 Cisco Systems, Inc. All rights reserved.
.br
