'\" t
.\"     Title: ncs-backup
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/26/2022
.\"    Manual: NCS Manual
.\"    Source: Cisco Systems, Inc.
.\"  Language: English
.\"
.TH "NCS\-BACKUP" "1" "01/26/2022" "Cisco Systems, Inc." "NCS Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncs-backup \- Command to backup and restore NCS data
.SH "SYNOPSIS"
.HP \w'\fBncs\-backup\fR\ 'u
\fBncs\-backup\fR [\-\-install\-dir\ \fIInstallDir\fR] [\-\-no\-compress]
.HP \w'\fBncs\-backup\fR\ 'u
\fBncs\-backup\fR \-\-restore [\fIBackup\fR] [\-\-install\-dir\ \fIInstallDir\fR] [\-\-non\-interactive]
.SH "DESCRIPTION"
.PP
The
\fBncs\-backup\fR
command can be used to backup and restore NCS CDB, state data, and config files for an NCS "system installation", i\&.e\&. one that was done with the
\fB\-\-system\-install\fR
option to the NCS installer (see
\m[blue]\fBncs\-installer(1)\fR\m[])\&. Unless the
\fB\-\-restore\fR
option is used, the command creates a backup\&. The backup is stored in the
\fIRunDir\fR/backups
directory, named with the NCS version and current date and time\&.
.SH "OPTIONS"
.PP
\fB\-\-restore [ \fR\fB\fIBackup\fR\fR\fB ]\fR
.RS 4
Restore a previously created backup\&. The
\fIBackup\fR
argument is either the name of a file in the
\fIRunDir\fR/backups
directory or the full path to a backup file\&. If the argument is omitted, unless the
\fB\-\-non\-interactive\fR
option is given, the command will offer selection from available backups\&.
.RE
.PP
\fB[ \-\-install\-dir \fR\fB\fIInstallDir\fR\fR\fB ]\fR
.RS 4
Specifies the directory for installation of NCS static files, like the
\fB\-\-install\-dir\fR
option to the installer\&. If this option is omitted,
/opt/ncs
will be used for
\fIInstallDir\fR\&.
.RE
.PP
\fB[ \-\-non\-interactive ]\fR
.RS 4
If this option is used, restore will proceed without asking for confirmation\&.
.RE
.PP
\fB[ \-\-no\-compress ]\fR
.RS 4
If this option is used, the backup will not be compressed (default is compressed)\&. The restore will uncompress if the backup is compressed, regardless of this option\&.
.RE
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2021, 2022 Cisco Systems, Inc. All rights reserved.
.br
