'\" t
.\"     Title: ncs-project-create
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/26/2022
.\"    Manual: NCS Manual
.\"    Source: Cisco Systems, Inc.
.\"  Language: English
.\"
.TH "NCS\-PROJECT\-CREATE" "1" "01/26/2022" "Cisco Systems, Inc." "NCS Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncs-project-create \- Command to create an NCS project
.SH "SYNOPSIS"
.HP \w'\fBncs\-project\ create\ \fR\ 'u
\fBncs\-project create \fR [OPTIONS] project\-name
.SH "DESCRIPTION"
.PP
Creates an NCS project, which consists of directories, configuration files and packages necessary to run an NCS system\&.
.PP
After running this command, the command:
\fIncs\-project update\fR
, should be run\&.
.PP
The NCS project connects an NCS installation with an arbitrary number of packages\&. This is declared in a
project\-meta\-data\&.xml
file which is located in the directory structure as created by this command\&.
.PP
The generated project should be seen as an initial project structure\&. Once generated, the
project\-meta\-data\&.xml
file should be manually modified\&. After the
project\-meta\-data\&.xml
file has been changed the command
\fIncs\-project setup\fR
should be used to bring the project content up to date\&.
.PP
A package, defined in the
project\-meta\-data\&.xml
file, can be located at a remote git repository and will then be cloned; or the package may be local to the project itself\&.
.PP
If a package version is specified to origin from a git repository, it may refer to a particular git commit hash, a branch or a tag\&. This way it is possible to either lock down an exact package version or always make use of the latest version of a particular branch\&.
.PP
A package can also be specified as
\fIlocal\fR, which means that it exists in place and no attempts to retrieve it will be made\&. Note however that it still needs to be a proper package with a
package\-meta\-data\&.xml
file\&.
.PP
There is also an option to create a project from an exported bundle\&. The bundle is generated using the
\fIncs\-project export\fR
command\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
Print a short help text and exit\&.
.RE
.PP
\fB\-d, \-\-dest\fR Directory
.RS 4
Specify the project (directory) location\&. The directory will be created if not existing\&. If not specified, the
\fIproject\-name\fR
will be used\&.
.RE
.PP
\fB\-u, \-\-ncs\-bin\-url \fR URL
.RS 4
Specify the exact URL pointing to an NCS install binary\&. Can be a
\fIhttp://\fR
or
\fIfile:///\fR
URL\&.
.RE
.PP
\fB\-\-from\-bundle=<bundle_path> \fR URL
.RS 4
Specify the exact path pointing to a bundled NCS Project\&. The bundle should have been created using the
\fIncs\-project export\fR
command\&.
.RE
.SH "EXAMPLES"
.PP
Generate a project using whatever NCS we have in our PATH\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  $ ncs\-project create foo\-project
  Creating directory: /home/my/foo\-project
  using locally installed NCS
  wrote project to /home/my/foo\-project
      
.fi
.if n \{\
.RE
.\}
.PP
Generate a project using a particular NCS release, located at a particular directory\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  $ ncs\-project create \-u file:///lab/releases/ncs\-4\&.0\&.1\&.linux\&.x86_64\&.installer\&.bin foo\-project
  Creating directory: /home/my/foo\-project
  cp /lab/releases/ncs\-4\&.0\&.1\&.linux\&.x86_64\&.installer\&.bin /home/my/foo\-project
  Installing NCS\&.\&.\&.
  INFO  Using temporary directory /tmp/ncs_installer\&.25681 to stage NCS installation bundle
  INFO  Unpacked ncs\-4\&.0\&.1 in /home/my/foo\-project/ncs\-installdir
  INFO  Found and unpacked corresponding DOCUMENTATION_PACKAGE
  INFO  Found and unpacked corresponding EXAMPLE_PACKAGE
  INFO  Generating default SSH hostkey (this may take some time)
  INFO  SSH hostkey generated
  INFO  Environment set\-up generated in /home/my/foo\-project/ncs\-installdir/ncsrc
  INFO  NCS installation script finished
  INFO  Found and unpacked corresponding NETSIM_PACKAGE
  INFO  NCS installation complete

  Installing NCS\&.\&.\&.done
  DON\*(AqT FORGET TO: source /home/my/foo\-project/ncs\-installdir/ncsrc
  wrote project to /home/my/foo\-project
      
.fi
.if n \{\
.RE
.\}
.PP
Generate a project using a project bundle created with the export command\&.
.sp
.if n \{\
.RS 4
.\}
.nf
  $  ncs\-project create \-\-from\-bundle=test_bundle\-1\&.0\&.tar\&.gz \-\-dest=installs
  Using NCS 4\&.2\&.0 found in /home/jvikman/dev/tailf/ncs_dir
  wrote project to /home/my/installs/test_bundle\-1\&.0
      
.fi
.if n \{\
.RE
.\}
.PP
After a project has been created, we need to have its
project\-meta\-data\&.xml
file updated before making use of the
\fIncs\-project update\fR
command\&.
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2021, 2022 Cisco Systems, Inc. All rights reserved.
.br
