'\" t
.\"     Title: ncs-project
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/26/2022
.\"    Manual: NCS Manual
.\"    Source: Cisco Systems, Inc.
.\"  Language: English
.\"
.TH "NCS\-PROJECT" "1" "01/26/2022" "Cisco Systems, Inc." "NCS Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncs-project \- Command to invoke NCS project commands
.SH "SYNOPSIS"
.HP \w'\fBncs\-project\ \fR\ 'u
\fBncs\-project \fR command [OPTIONS]
.SH "DESCRIPTION"
.PP
This command is used to invoke one of the NCS project commands\&.
.PP
An NCS project is a complete running NCS installation\&. It can contain all the needed packages and the config data that is required to run the system\&.
.PP
The NCS project is described in a project\-meta\-data\&.xml file according to the
tailf\-ncs\-project\&.yang
Yang model\&. By using the ncs\-project commands, the complete project can be populated\&. This can be used for encapsulating NCS demos or even a full blown turn\-key system\&.
.PP
Each command is described in its own man\-page, which can be displayed by calling:
\fBncs\-project help\fR\fI<command>\fR
.PP
The
\fIOPTIONS\fR
are forwarded to the the invoked script verbatim\&.
.SH "COMMAND"
.PP
\fBcreate\fR
.RS 4
Create a new NCS project\&.
.RE
.PP
\fBexport\fR
.RS 4
Export an NCS project\&.
.RE
.PP
\fBgit\fR
.RS 4
For each git package repository, execute an arbitrary git command\&.
.RE
.PP
\fBupdate\fR
.RS 4
Populate a new NCS project or update an existing project\&. NOTE: Was called \*(Aqsetup\*(Aq earlier\&.
.RE
.PP
\fBhelp\fR command
.RS 4
Display the man\-page for the specified NCS project command\&.
.RE
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2021, 2022 Cisco Systems, Inc. All rights reserved.
.br
