'\" t
.\"     Title: ncs-collect-tech-report
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/26/2022
.\"    Manual: NCS Manual
.\"    Source: Cisco Systems, Inc.
.\"  Language: English
.\"
.TH "NCS\-COLLECT\-TECH\-" "1" "01/26/2022" "Cisco Systems, Inc." "NCS Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ncs-collect-tech-report \- Command to collect diagnostics from an NCS installation that has been installed with the \-\-system\-install option
.SH "SYNOPSIS"
.HP \w'\fBncs\-collect\-tech\-report\fR\ 'u
\fBncs\-collect\-tech\-report\fR [\-\-install\-dir\ \fIInstallDir\fR] [\-\-full] [\-\-num\-debug\-dumps\ Integer]
.SH "DESCRIPTION"
.PP
The
\fBncs\-collect\-tech\-report\fR
command can be used to collect diagnostics from an NCS installation\&. The resulting diagnostics file contains information that is useful to Cisco support to diagnose problems and errors\&.
.PP
If the NCS daemon is running, runtime data from the running daemon will be collected\&. If the NCS daemon is not running, only static files will be collected\&.
.SH "OPTIONS"
.PP
\fB[ \-\-install\-dir \fR\fB\fIInstallDir\fR\fR\fB ]\fR
.RS 4
Specifies the directory for installation of NCS static files, like the
\fB\-\-install\-dir\fR
option to the installer\&. If this option is omitted,
/opt/ncs
will be used for
\fIInstallDir\fR\&.
.RE
.PP
\fB[ \-\-full ]\fR
.RS 4
This option is used to also include a full backup (as produced by
\fBncs\-backup\fR) of the system\&. This makes it sometimes possible for Cisco support to reproduce issues locally\&.
.RE
.PP
\fB[ \-\-num\-debug\-dumps \fR\fB\fICount\fR\fR\fB ]\fR
.RS 4
This option is sometimes useful when a resource leak (memory/file descriptors) is suspected\&. It instructs the
\fBncs\-collect\-tech\-report\fR
script to run the command
\fBncs \-\-debug\-dump\fR
multiple times\&.
.RE
.SH "AUTHOR"
.br
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2021, 2022 Cisco Systems, Inc. All rights reserved.
.br
