/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-xr-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-xr-stats.yang */
public class tailfNedCiscoIosXrStats extends ConfNamespace {
    public static final int hash = 465174368;
    public int hash() {
        return tailfNedCiscoIosXrStats.hash;
    }

    public static final String id = "_cisco-iosxr-cli-7.38:cisco-iosxr-cli-7.38#http://tail-f.com/ned/cisco-ios-xr-stats";
    public String id() {
        return tailfNedCiscoIosXrStats.id;
    }

    public static final String uri = "_cisco-iosxr-cli-7.38:cisco-iosxr-cli-7.38#http://tail-f.com/ned/cisco-ios-xr-stats";
    public String uri() {
        return tailfNedCiscoIosXrStats.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedCiscoIosXrStats.uri);
    }

    public static final String prefix = "cisco-ios-xr-stats";
    public String prefix() {
        return tailfNedCiscoIosXrStats.prefix;
    }

    public tailfNedCiscoIosXrStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _vid = 1545846517;
    public static final String _vid_ = "vid";
    public static final int    _admin_mode = 1053225543;
    public static final String _admin_mode_ = "admin-mode";
    public static final int    _optics_type = 1119497228;
    public static final String _optics_type_ = "optics-type";
    public static final int    _controller_state = 675761618;
    public static final String _controller_state_ = "controller-state";
    public static final int    _rev_number = 52820274;
    public static final String _rev_number_ = "rev-number";
    public static final int    _part_number = 461358154;
    public static final String _part_number_ = "part-number";
    public static final int    _platform = 688179959;
    public static final String _platform_ = "platform";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _exec = 1716494663;
    public static final String _exec_ = "exec";
    public static final int    _answer = 638178487;
    public static final String _answer_ = "answer";
    public static final int    _question = 1260341232;
    public static final String _question_ = "question";
    public static final int    _parent_interface = 169482247;
    public static final String _parent_interface_ = "parent-interface";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _pid = 397036642;
    public static final String _pid_ = "pid";
    public static final int    _crypto = 1089763547;
    public static final String _crypto_ = "crypto";
    public static final int    _device_id = 669279939;
    public static final String _device_id_ = "device-id";
    public static final int    _serial_number = 544353266;
    public static final String _serial_number_ = "serial-number";
    public static final int    _cdp = 1086691831;
    public static final String _cdp_ = "cdp";
    public static final int    _port_id = 411479338;
    public static final String _port_id_ = "port-id";
    public static final int    _capability = 1251322185;
    public static final String _capability_ = "capability";
    public static final int    _sn = 1198281017;
    public static final String _sn_ = "sn";
    public static final int    _any = 383440309;
    public static final String _any_ = "any";
    public static final int    _auto_prompts = 490621390;
    public static final String _auto_prompts_ = "auto-prompts";
    public static final int    _controllers = 1302107053;
    public static final String _controllers_ = "controllers";
    public static final int    _descr = 114576946;
    public static final String _descr_ = "descr";
    public static final int    _instance = 136214150;
    public static final String _instance_ = "instance";
    public static final int    _hold_time = 204730640;
    public static final String _hold_time_ = "hold-time";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _time_remaining = 196459818;
    public static final String _time_remaining_ = "time-remaining";
    public static final int    _local_interface = 950762803;
    public static final String _local_interface_ = "local-interface";
    public static final int    _oui_number = 1929286621;
    public static final String _oui_number_ = "oui-number";
    public static final int    _chassis_id = 1476535866;
    public static final String _chassis_id_ = "chassis-id";
    public static final int    _clear = 634788371;
    public static final String _clear_ = "clear";
    public static final int    _lldp = 830250803;
    public static final String _lldp_ = "lldp";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _any_hidden = 1109261217;
    public static final String _any_hidden_ = "any-hidden";
    public static final int    _args = 578380655;
    public static final String _args_ = "args";
    public static final int    _date_code = 1902762841;
    public static final String _date_code_ = "date-code";
    public static final int    _transceiver_vendor_details = 2035727050;
    public static final String _transceiver_vendor_details_ = "transceiver-vendor-details";
    public static final int    _reload = 1336127569;
    public static final String _reload_ = "reload";
    public static final int    _Optics = 1744301120;
    public static final String _Optics_ = "Optics";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _copy = 1887233912;
    public static final String _copy_ = "copy";
    public static final int    _inventory = 1127425688;
    public static final String _inventory_ = "inventory";
    public static final int    _form_factor = 605079377;
    public static final String _form_factor_ = "form-factor";
    public static final int    _show = 1568086057;
    public static final String _show_ = "show";
}
