#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: tmp_fxs/tailf-netconf-ncs.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-netconf-ncs.yang


class ns(object):
    hash = 1145948134

    id = "http://tail-f.com/ns/netconf/ncs"

    uri = "http://tail-f.com/ns/netconf/ncs"

    prefix = "ncsnc"

    ncsnc_no_overwrite = 2064525500
    ncsnc_no_overwrite_ = "no-overwrite"
    ncsnc_commit_cq_failed = 4
    ncsnc_commit_cq_failed_ = "failed"
    ncsnc_rollback_on_error = 1
    ncsnc_rollback_on_error_ = "rollback-on-error"
    ncsnc_block_others = 1263742525
    ncsnc_block_others_ = "block-others"
    ncsnc_trace_id = 1065151221
    ncsnc_trace_id_ = "trace-id"
    ncsnc_local_node = 1170793894
    ncsnc_local_node_ = "local-node"
    ncsnc_choice_unlock_id = 21514334
    ncsnc_choice_unlock_id_ = "choice-unlock-id"
    ncsnc_case_native = 386518560
    ncsnc_case_native_ = "case-native"
    ncsnc_choice_lsa = 1376297560
    ncsnc_choice_lsa_ = "choice-lsa"
    ncsnc_tag = 21925559
    ncsnc_tag_ = "tag"
    ncsnc_no_out_of_sync_check = 1635449845
    ncsnc_no_out_of_sync_check_ = "no-out-of-sync-check"
    ncsnc_choice_sync_check = 2088008581
    ncsnc_choice_sync_check_ = "choice-sync-check"
    ncsnc_error_option = 795048046
    ncsnc_error_option_ = "error-option"
    ncsnc_use_lsa = 526283796
    ncsnc_use_lsa_ = "use-lsa"
    ncsnc_atomic = 651133906
    ncsnc_atomic_ = "atomic"
    ncsnc_device = 617911018
    ncsnc_device_ = "device"
    ncsnc_timeout = 614210192
    ncsnc_timeout_ = "timeout"
    ncsnc_status = 1950810920
    ncsnc_status_ = "status"
    ncsnc_no_deploy = 273586140
    ncsnc_no_deploy_ = "no-deploy"
    ncsnc_dryrun = 12428042
    ncsnc_dryrun_ = "dryrun"
    ncsnc_outformat = 2033658489
    ncsnc_outformat_ = "outformat"
    ncsnc_commit_cq_timeout = 2
    ncsnc_commit_cq_timeout_ = "timeout"
    ncsnc_continue_on_error = 0
    ncsnc_continue_on_error_ = "continue-on-error"
    ncsnc_infinity = 1378257424
    ncsnc_infinity_ = "infinity"
    ncsnc_timeout_choice = 1513740746
    ncsnc_timeout_choice_ = "timeout-choice"
    ncsnc_no_revision_drop = 355519481
    ncsnc_no_revision_drop_ = "no-revision-drop"
    ncsnc_dry_run = 1450488329
    ncsnc_dry_run_ = "dry-run"
    ncsnc_dry_run_result = 1526395882
    ncsnc_dry_run_result_ = "dry-run-result"
    ncsnc_reverse = 1011351090
    ncsnc_reverse_ = "reverse"
    ncsnc_commit_cq_async = 0
    ncsnc_commit_cq_async_ = "async"
    ncsnc_case_cli = 1248658608
    ncsnc_case_cli_ = "case-cli"
    ncsnc_unlock = 1383788173
    ncsnc_unlock_ = "unlock"
    ncsnc_c_non_service_config = 163842291
    ncsnc_c_non_service_config_ = "c-non-service-config"
    ncsnc_lock = 95781586
    ncsnc_lock_ = "lock"
    ncsnc_commit_cq_deleted = 3
    ncsnc_commit_cq_deleted_ = "deleted"
    ncsnc_result_xml = 558977045
    ncsnc_result_xml_ = "result-xml"
    ncsnc_cli = 1771971819
    ncsnc_cli_ = "cli"
    ncsnc_no_lsa = 1557783121
    ncsnc_no_lsa_ = "no-lsa"
    ncsnc_async = 1368962940
    ncsnc_async_ = "async"
    ncsnc_reason = 565156039
    ncsnc_reason_ = "reason"
    ncsnc_lsa_node = 919917514
    ncsnc_lsa_node_ = "lsa-node"
    ncsnc_name = 1998270519
    ncsnc_name_ = "name"
    ncsnc_discard_non_service_config = 441364055
    ncsnc_discard_non_service_config_ = "discard-non-service-config"
    ncsnc_reconcile = 652237750
    ncsnc_reconcile_ = "reconcile"
    ncsnc_with_service_meta_data = 2044325681
    ncsnc_with_service_meta_data_ = "with-service-meta-data"
    ncsnc_operation_mode = 53338359
    ncsnc_operation_mode_ = "operation-mode"
    ncsnc_native = 472211213
    ncsnc_native_ = "native"
    ncsnc_no_networking = 479600569
    ncsnc_no_networking_ = "no-networking"
    ncsnc_failed_device = 1735357793
    ncsnc_failed_device_ = "failed-device"
    ncsnc_data = 535242711
    ncsnc_data_ = "data"
    ncsnc_commit_queue = 159457261
    ncsnc_commit_queue_ = "commit-queue"
    ncsnc_commit_cq_completed = 1
    ncsnc_commit_cq_completed_ = "completed"
    ncsnc_stop_on_error = 2
    ncsnc_stop_on_error_ = "stop-on-error"
    ncsnc_keep_non_service_config = 1090229776
    ncsnc_keep_non_service_config_ = "keep-non-service-config"
    ncsnc_sync = 2047869128
    ncsnc_sync_ = "sync"
    ncsnc_bypass = 1000536498
    ncsnc_bypass_ = "bypass"
    ncsnc_id = 1279252765
    ncsnc_id_ = "id"
    ncsnc_wait_device = 91964558
    ncsnc_wait_device_ = "wait-device"
    ncsnc_case_xml = 1045595144
    ncsnc_case_xml_ = "case-xml"
